signEquilibrium: -1
signFlexor: 1
signExtensor: -1
signEncoder: -1
signJoint: 1
nameFlexor: "biceps"
nameExtensor: "triceps"
nameEncoder: "elbow_encoder"
servoRange: 6.2832
minAngle: -0.85
maxAngle: 0.85
angleOffset: 0