calibrated: 1
signEquilibrium: -1
signFlexor: 1
signExtensor: -1
signEncoder: -1
signJoint: 1
name: "elbow"
nameFlexor: "biceps"
nameExtensor: "triceps"
nameEncoder: "elbow_encoder"
servoRange: 6.2832
servoOffset: 0
minAngle: -0.85
maxAngle: 0.65
angleOffset: 0
gains:
    P: 0.06
    D: 0.2