signEquilibrium: 1
signFlexor: 1
signExtensor: -1
signEncoder: 1
signJoint: 1
nameFlexor: "shoulder_flexor"
nameExtensor: "shoulder_extensor"
nameEncoder: "shoulder_roll_encoder"
servoRange: 12.5664
servoOffset: 0
minAngle: -1.4
maxAngle: 2.4
angleOffset: 1.05
gains:
    P: 0.03
    D: 0.015