hand_dof1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: hand_dof1
    joint_speed: 6.0
    motor:
        id: 22
        init: 512
        min: 0
        max: 1023
