horizontal_adductor_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: horizontal_adductor
    joint_speed: 100
    motor:
        id: 17
        init: 6143
        min: 0
        max: 12287