shoulder_flexor_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: shoulder_flexor
    joint_speed: 10
    motor:
        id: 13
        init: 6143
        min: 0
        max: 12287