shoulder_extensor_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: shoulder_extensor
    joint_speed: 10
    motor:
        id: 14
        init: 6143
        min: 0
        max: 12287