pose_mode: false
debug_mode: false
num_joints: 7
control_gain: 0.01
control_gain_pose: 0.0075
max_joint_vel: 0.3
scale_translation: 25.0
scale_rotation: 40.0
ik_diag_weights_js: [0.75, 1.0, 0.75, 1.0, 1.0, 1.0, 1.0]
ik_diag_weights_ts: [1.0, 1.0, 1.0, 0.75, 0.75, 0.75]